### ISSUE TITLE
Issue when decompressing bzip2

### ISSUE THREAD

**Issue by hallas** [aphistic/go.Zamara#1]
Hello

I've got a similar program to yours however for extracting MPQ archives, Go gives me an error when trying to decompress a bzip2 file inside the archive.

In my case, I know I'm at the right file position (I see the magic value and the compression byte) and I also know that I have the correct compressed file size and real file size (I tried both as it looks like you you the decompressed file size). However, all I get is this error:

`bzip2 data invalid: block checksum mismatch`

Do you by any chance know why this happens?

All the best

**Comment by aphistic** [comment]
Hey! 

My best guess would be you might be cutting off the end of a buffer or something, leading the block to be the wrong size and the checksum failing.  I don't know a lot about the inner workings of bzip2 but that's what I would check if I got that error.

It's been a long time since I've worked on this project so I'm sorry that I don't have a better answer than this. =/

**Comment by hallas** [comment]
ok. thank you :)
